# Generated by Django 4.2.16 on 2024-10-28 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('game_mode_id', models.AutoField(primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('TOURNAMENT', 'Tournament'), ('TRAINING', 'Training with AI'), ('1VS1', 'One vs One')], default='1VS1', max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'gameMode',
            },
        ),
        migrations.CreateModel(
            name='GameTable',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('background_image', models.CharField(max_length=255)),
                ('xp_required', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gameTable',
            },
        ),
        migrations.CreateModel(
            name='GameSessions',
            fields=[
                ('gameSession_id', models.AutoField(primary_key=True, serialize=False)),
                ('player1_id', models.IntegerField()),
                ('player2_id', models.IntegerField(null=True)),
                ('winner_id', models.IntegerField(null=True)),
                ('loser_id', models.IntegerField(null=True)),
                ('score_player1', models.IntegerField(default=0)),
                ('score_player2', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('paused_time', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for opponent'), ('IN_PROGRESS', 'Game in progress'), ('PAUSED', 'Game paused'), ('FINISHED', 'Game finished')], default='WAITING', max_length=20)),
                ('gameTable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gametable')),
                ('mode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamemode')),
            ],
            options={
                'db_table': 'GameSessions',
            },
        ),
    ]
