# Generated by Django 4.2.16 on 2024-12-22 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSessions',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('score_player1', models.IntegerField(default=0)),
                ('score_player2', models.IntegerField(default=0)),
                ('winner_score', models.IntegerField(default=0)),
                ('loser_score', models.IntegerField(default=0)),
                ('player1_xp_gain', models.IntegerField(default=0)),
                ('player2_xp_gain', models.IntegerField(default=0)),
                ('is_paused', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for opponent'), ('IN_PROGRESS', 'Game in progress'), ('PAUSED', 'Game paused'), ('FINISHED', 'Game finished')], default='WAITING', max_length=20)),
                ('loser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_games', to=settings.AUTH_USER_MODEL)),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_session',
                'ordering': ['-start_time'],
            },
        ),
    ]
