# Generated by Django 4.2.16 on 2024-12-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gamesessions_loser_alter_gamesessions_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesessions',
            name='background_id',
        ),
        migrations.RemoveField(
            model_name='gamesessions',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='gamesessions',
            name='player1_ready',
        ),
        migrations.RemoveField(
            model_name='gamesessions',
            name='player2_ready',
        ),
        migrations.AddField(
            model_name='gamesessions',
            name='loser_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesessions',
            name='player1_xp_gain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesessions',
            name='player2_xp_gain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesessions',
            name='winner_score',
            field=models.IntegerField(default=0),
        ),
    ]
