# Generated by Django 4.2.16 on 2024-10-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_populate_gametable'),
        ('game', '0003_populate_gameMode'),
    ]

    operations = [
    ]
