"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
import sys
import hvac

with open('/tmp/token.txt', 'r') as f:
    root_token = f.read().strip()
    f.close()
vault_url = os.environ.get('VAULT_ADDR')

# print(root_token)
# print(vault_url)

def put_vault_secret(token, secret_path, secret_data):
    """
    Puts a secret in HashiCorp Vault.

    :param token: The Vault authentication token.
    :param secret_path: The path to the secret (e.g., 'secret/my_secret')
    :param secret_data: The secret data to store.
    :return: A message indicating success or failure.
    """
    try:
        # Create a Vault client
        client = hvac.Client(url=vault_url, token=token)
        
        # Check if client is authenticated
        if not client.is_authenticated():
            raise Exception("Vault authentication failed.")
        
        # Put the secret
        client.secrets.kv.v2.create_or_update_secret(path=secret_path, secret=secret_data)
        
        return "Secret stored successfully."

    except Exception as e:
        return f"Error storing secret: {str(e)}"

# put_vault_secret(root_token, 'django', {'tabi3a': 'my_secret'})
def get_vault_secret(token, secret_path):
    """
    Fetches a secret from HashiCorp Vault.

    :param token: The Vault authentication token.
    :param secret_path: The path to the secret (e.g., 'secret/my_secret')
    :return: The secret data or an error message.
    """
    try:
        # Create a Vault client
        client = hvac.Client(url=vault_url, token=token)
        
        # Check if client is authenticated
        if not client.is_authenticated():
            raise Exception("Vault authentication failed.")
        
        # Fetch the secret
        secret = client.secrets.kv.read_secret_version(path=secret_path)
        # print(secret)
        # Return the data part of the secret
        return secret['data']['data']  # Adjust based on your secret engine version

    except Exception as e:
        return f"Error fetching secret: {str(e)}"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

HOSTNAME = os.environ.get('HOSTNAME_ENV', 'localhost')
PORT = os.environ.get('PORT_ENV', '443')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_vault_secret(root_token, 'django')['SECRET_KEY']
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = get_vault_secret(root_token, 'django')['SOCIAL_AUTH_GOOGLE_OAUTH2_KEY']
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = get_vault_secret(root_token, 'django')['SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET']
SOCIAL_AUTH_INTRA42_KEY = get_vault_secret(root_token, 'django')['SOCIAL_AUTH_INTRA42_KEY']
SOCIAL_AUTH_INTRA42_SECRET = get_vault_secret(root_token, 'django')['SOCIAL_AUTH_INTRA42_SECRET']
SOCIAL_AUTH_INTRA42_REDIRECT_URI = f'https://{HOSTNAME}/api/social-auth/complete/intra42/'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Application definition
INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'channels',
    'UserManagement',
    'social_django',
    'core',
    'channels_redis',
    'rest_framework.authtoken',
    'game',
    'Chat',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    'intra42': {
        'SCOPE': [
            'public',
        ],
    },
}

# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    # this ensures authentication errors are handled properly
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

# backend/core/settings.py

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # Add your template directories here
            os.path.join(BASE_DIR, 'game', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#for postgres
POSTGRES_DB = get_vault_secret(root_token, 'postgres')['POSTGRES_DB']
POSTGRES_USER = get_vault_secret(root_token, 'postgres')['POSTGRES_USER']
POSTGRES_PASSWORD = get_vault_secret(root_token, 'postgres')['POSTGRES_PASSWORD']
POSTGRES_HOST = get_vault_secret(root_token, 'postgres')['POSTGRES_HOST']
POSTGRES_PORT = 5432


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': POSTGRES_DB,
        'USER': POSTGRES_USER,
        'PASSWORD': POSTGRES_PASSWORD,
        'HOST': POSTGRES_HOST,
        'PORT': POSTGRES_PORT,
    }
}



#for sqlite
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

AUTH_USER_MODEL = 'UserManagement.User'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# # for  profile pictures
# STATIC_URL = "profile_pictures/" # URL prefix for your profile pictures

# STATICFILES_DIRS = [
#     BASE_DIR / "profile_pictures", # Path to your profile pictures directory
# ]

# # for badges
# BADGES_URL = "/badges/"  # Custom URL prefix for badges
# BADGES_DIR = BASE_DIR / "badges" # Path to your badges directory






# Base settingsS
STATIC_URL = '/static/'  # Base URL for all static files
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Where collectstatic will put files

# Your specific static directories
STATICFILES_DIRS = [
    ('badges', BASE_DIR / 'badges'),           # This will create /static/badges/
    ('profile_pictures', BASE_DIR / 'profile_pictures')  # This will create /static/profile_pictures/
]

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=20),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',  # Use HMAC with SHA-256
    'SIGNING_KEY': SECRET_KEY,  # Use your Django project's secret key to sign the JWTs
    'VERIFYING_KEY': None,  # Only needed for asymmetric signing (RS256, etc.)
    'AUTH_HEADER_TYPES': ('Bearer',),  # This means the Authorization header will look like: Authorization: Bearer <token>
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'ACCESS_TOKEN_CLASS': 'core.serializers.CustomAccessToken',
}

SESSION_COOKIE_SAMESITE = 'None'

CSRF_COOKIE_SAMESITE = 'None'

CORS_ALLOW_CREDENTIALS = True

# ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = [
    f'{HOSTNAME}:{PORT}',
    '127.0.0.1',
    'localhost',
    f'{HOSTNAME}',
    f'{HOSTNAME}:{PORT}',
    'e2r9p7.1337.ma'
]

AUTHENTICATION_BACKENDS = (
    'core.GoogleOauth2.CustomGoogleOAuth2',  # Google OAuth
    'core.intra42.Intra42OAuth2',  # Custom Intra42 backend
    'django.contrib.auth.backends.ModelBackend',  # Default authentication
)


LOGIN_REDIRECT_URL = f'https://{HOSTNAME}:{PORT}/Dashboard'
LOGOUT_REDIRECT_URL = f'https://{HOSTNAME}:{PORT}/'

SOCIAL_AUTH_URL_NAMESPACE = 'social'

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)


# Optional: You can configure scopes or permissions as needed
SOCIAL_AUTH_INTRA42_SCOPE = ['public']


# Caching Configuration (for game state and other cache needs)
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://redis:6379/1',  # Using Redis database 1 for caching
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}


# settings.py
SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    'access_type': 'offline',
    'prompt': 'consent',
}

# Add this if you're using social-auth-app-django
SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS = [
    f'{HOSTNAME}:5173',
    '10.12.2.9:5173',
]

SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'email', 
    'profile',
]


CORS_ALLOW_ALL_ORIGINS = False  # Don't use this in production
CORS_ALLOWED_ORIGINS = [
    f"https://{HOSTNAME}",
    f"http://{HOSTNAME}:{PORT}",
    f"http://{HOSTNAME}:5173",
    f"https://{HOSTNAME}:5173",
    "https://api.intra.42.fr",
] # todo: to be changed in production
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = False