version: '3.8'

networks:
  ft_transcendence_network:
    name: ft_transcendence_network

volumes:
  certs:
    name: certs
  VaultVol:
      driver_opts:
        o: bind
        type: local
        device: /Users/ahmaymou/ft_transcendence/app/vault

services:
  # PostgreSQL Database
  ft_transcendence_db:
    container_name: ft_transcendence_db
    image: postgres:14
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MAX_CONNECTIONS=200
    volumes:
      - ./app/data/postgresql:/var/lib/postgresql/data
    networks:
      - ft_transcendence_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 45s
      interval: 5s
      timeout: 30s
    restart: always

  # Django Backend
  backend:
    container_name: backend
    build: app/backend/.
    env_file:
      - app/backend/.env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=core.settings
      - VAULT_ADDR=http://vault:8200
    depends_on:
      ft_transcendence_db:
        condition: service_healthy
      vault:
        condition: service_healthy
    networks:
      - ft_transcendence_network
    volumes:
      - ./app/backend:/app/backend
      - ./app/vault/token.txt:/tmp/token.txt
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOSTNAME}:8000/api/health/"]
      start_period: 45s
      interval: 10s
      timeout: 30s
    restart: always

  # React Frontend
  frontend:
    container_name: frontend
    build: app/frontend/.
    networks:
      - ft_transcendence_network
    volumes:
      - ./app/frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      backend:
        condition: service_healthy
    restart: always

  # Redis
  redis:
    container_name: redis
    image: redis:7
    networks:
      - ft_transcendence_network
    volumes:
      - ./app/data/redis:/data
    depends_on:
      backend:
        condition: service_healthy
    restart: always


############ WAF ############
  appsec-agent:
      image: ghcr.io/openappsec/agent:${APPSEC_VERSION}
      container_name: appsec-agent
      environment:
        - SHARED_STORAGE_HOST=appsec-shared-storage
        - LEARNING_HOST=appsec-smartsync
        - TUNING_HOST=appsec-tuning-svc
        - https_proxy=${APPSEC_HTTPS_PROXY}
        - user_email=${USER_EMAIL}
        - AGENT_TOKEN=${APPSEC_AGENT_TOKEN}
        - autoPolicyLoad=${APPSEC_AUTO_POLICY_LOAD}
        - registered_server="StarServe AppSec"
      ipc: shareable
      volumes:
        - ${APPSEC_CONFIG}:/etc/cp/conf
        - ${APPSEC_DATA}:/etc/cp/data
        - ${APPSEC_LOGS}:/var/log/nano_agent
        - ${APPSEC_LOCALCONFIG}:/ext/appsec
        - ${RUNNING_SCRIPT}:/ext/retriveFromVault.sh
        - ./app/vault/token.txt:/tmp/token.txt
        - ${APPSEC_ADVANCED_AI}:/advanced-model/open-appsec-advanced-model.tgz:rw
      command: /cp-nano-agent
      restart: always
      depends_on:
        vault:
          condition: service_healthy
  appsec-nginx:
    image: ghcr.io/openappsec/nginx-attachment:${APPSEC_VERSION}
    container_name: appsec-nginx
    ipc: service:appsec-agent
    volumes:
      - ${NGINX_CONF_FILE}:/etc/nginx/conf.d/starserve.conf
      - ./app/nginx/tools/generate_ssl.sh:/app/generate_ssl.sh
    user: root
    command: >
      sh -c "
        apk update && apk add openssl  || ls -la /app/generate_ssl.sh &&
        chmod +x /app/generate_ssl.sh &&
        sh /app/generate_ssl.sh &&
        nginx -g 'daemon off;'
      "
    networks:
      - ft_transcendence_network
    depends_on:
      - backend
      - frontend
    ports:
      # - "80:80"
      - "443:443"

  appsec-smartsync:
    profiles:
      - standalone
    image: ghcr.io/openappsec/smartsync:${APPSEC_VERSION}
    container_name: appsec-smartsync
    environment:
      - SHARED_STORAGE_HOST=appsec-shared-storage
    depends_on:
      - appsec-shared-storage
  appsec-shared-storage:
    profiles:
      - standalone
    image: ghcr.io/openappsec/smartsync-shared-files:${APPSEC_VERSION}
    container_name: appsec-shared-storage
    ipc: service:appsec-agent
    # user: root
    volumes:
      - ${SMART_SYNC_STORAGE}:/db:z
    networks:
      - ft_transcendence_network
  appsec-tuning-svc:
    profiles:
      - standalone
    image: ghcr.io/openappsec/smartsync-tuning:${APPSEC_VERSION}
    container_name: appsec-tuning-svc
    environment:
      - SHARED_STORAGE_HOST=appsec-shared-storage
      - QUERY_DB_PASSWORD=${DB_PASSWORD}
      - QUERY_DB_HOST=${DB_HOST}
      - QUERY_DB_USER=${DB_USER}
    volumes:
      - ${APPSEC_CONFIG}:/etc/cp/conf
    depends_on:
      - appsec-shared-storage
      - appsec-db
    networks:
      - ft_transcendence_network
  appsec-db:
    profiles:
      - standalone
    image: postgres
    container_name: appsec-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER} 
    volumes:
      - ${POSTGRES_STORAGE}:/var/lib/postgresql/data
    networks:
      - ft_transcendence_network

############ VAULT ############
  vault:
    container_name: vault
    build: ./app/vault/.
    ports:
      - "8200:8200"
      - "8201:8201"
    volumes:
      - ./app/vault/token.txt:/tmp/token.txt
    env_file:
      - ./app/vault/.env
    healthcheck:
      test: ["CMD", "sleep", "15"]
      interval: 10s
      timeout: 30s
      retries: 5
    networks:
      - ft_transcendence_network

  #setup for elasticsearch
  # comment this :
  # setup:
  #   container_name: setup
  #   build: ./app/elk/setup/.
  #   volumes:
  #     - certs:/usr/share/elasticsearch/config/certs
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - ft_transcendence_network
  #   env_file:
  #     - .env
  #   healthcheck:
  #     test: ['CMD-SHELL', '[ -f /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.crt ]']
  #     interval: 1s
  #     timeout: 5s
  #     retries: 120
  

  # # Elasticsearch
  # elasticsearch:
  #   container_name: elasticsearch
  #   depends_on:
  #     setup:
  #       condition: service_healthy
  #   build: ./app/elk/elasticsearch/.
  #   volumes:
  #     - certs:/usr/share/elasticsearch/config/certs
  #     - ./app/data/elasticsearch:/usr/share/elasticsearch/data
  #   ports:
  #     - '9200:9200'
  #   env_file:
  #     - .env
  #   networks:
  #     - ft_transcendence_network
  #   mem_limit: ${MEM_LIMIT}
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   restart: always

  # # Kibana
  # kibana:
  #   container_name: kibana
  #   depends_on:
  #     setup:
  #       condition: service_healthy
  #   build: ./app/elk/kibana/.
  #   volumes:
  #     - certs:/usr/share/kibana/config/certs
  #     - ./app/data/kibana:/usr/share/kibana/data
  #   ports:
  #     - '5601:5601'
  #   env_file:
  #     - .env
  #   networks:
  #     - ft_transcendence_network
  #   mem_limit: ${MEM_LIMIT}
  #   restart: always

  # # Logstash
  # logstash:
  #   container_name: logstash
  #   depends_on:
  #     setup:
  #       condition: service_healthy
  #   build: ./app/elk/logstash/.
  #   volumes:
  #     - certs:/usr/share/logstash/certs
  #     - ./app/nginx/logs/access.log:/usr/share/logstash/nginx/access.log
  #   env_file:
  #     - .env
  #   networks:
  #     - ft_transcendence_network  
  #   restart: always

