# Generated by Django 4.2.16 on 2024-10-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='last_message_id',
            new_name='last_message',
        ),
    ]
