# Generated by Django 4.2.16 on 2025-01-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
    ]
