# Generated by Django 4.2.16 on 2024-12-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='status',
        ),
        migrations.AddField(
            model_name='conversation',
            name='blocked_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
