# Generated by Django 4.2.16 on 2024-11-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_rename_last_message_id_conversation_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_key',
            field=models.CharField(default='0_0', max_length=20),
        ),
    ]
