# Generated by Django 4.2.15 on 2024-09-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('new_password', models.CharField(default='', max_length=30)),
                ('confirm_password', models.CharField(default='', max_length=30)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=10)),
                ('display_name', models.CharField(default='', max_length=30)),
                ('bio', models.TextField(blank=True, default='')),
                ('profile_picture', models.ImageField(default='profile_pictures/avatar.jpg', upload_to='profile_pictures/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
