# Generated by Django 4.2.16 on 2024-12-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_custom_profile_picture",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="has_custom_username",
            field=models.BooleanField(default=False),
        ),
    ]
