# Generated by Django 4.2.16 on 2025-01-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
        migrations.AddField(
            model_name='user',
            name='is_logged_with_oauth_for_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
