# Generated by Django 4.2.16 on 2024-12-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='winner',
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tournamentparticipant',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentparticipant',
            name='user',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.DeleteModel(
            name='TournamentParticipant',
        ),
    ]
