# Generated by Django 4.2.16 on 2024-12-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserManagement", "0002_user_has_custom_profile_picture_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="has_custom_profile_picture",
        ),
        migrations.RemoveField(
            model_name="user",
            name="has_custom_username",
        ),
    ]
