# Generated by Django 4.2.16 on 2024-11-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManagement", "0002_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="confirm_password",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="user",
            name="new_password",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
