# Generated by Django 4.2.16 on 2025-01-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_remove_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_logged_with_oauth_for_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
