# Generated by Django 4.2.16 on 2025-01-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_user_blocked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blocked_users',
        ),
    ]
