# Generated by Django 4.2.16 on 2024-12-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_remove_user_has_custom_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_custom_profile_picture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_custom_username',
            field=models.BooleanField(default=False),
        ),
    ]
