# Generated by Django 4.2.16 on 2024-11-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_alter_user_confirm_password_alter_user_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='new_password',
        ),
    ]
