# Generated by Django 4.2.16 on 2024-12-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_remove_tournament_winner_and_more'),
        ('UserManagement', '0004_alter_user_date_joined'),
    ]

    operations = [
    ]
