# Generated by Django 4.2.16 on 2024-11-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0005_user_confirm_password_user_new_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='new_password',
        ),
    ]
