# Generated by Django 4.2.15 on 2024-09-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0005_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
