# Generated by Django 4.2.16 on 2025-01-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0006_user_is_2fa_enabled_user_otp_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
