# Generated by Django 4.2.16 on 2025-01-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0008_alter_user_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_secret',
            field=models.IntegerField(default=0),
        ),
    ]
