# Generated by Django 4.2.15 on 2024-09-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0009_user_bio_user_display_name_user_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='new_password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
