# Generated by Django 4.2.16 on 2025-01-11 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0010_alter_notification_message_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
