# Generated by Django 5.1.3 on 2024-11-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0010_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/avatar.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
