# Generated by Django 4.2.15 on 2024-09-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0010_user_confirm_password_user_new_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/avatar.jpg', upload_to='profile_pictures/'),
        ),
    ]
