# Generated by Django 5.1.3 on 2024-11-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0014_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_custom_profile_picture',
            field=models.BooleanField(default=False),
        ),
    ]
