# Generated by Django 5.1.3 on 2024-11-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0015_user_is_custom_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_custom_profile_picture',
        ),
    ]
