# Generated by Django 4.2.16 on 2024-11-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0016_remove_user_is_custom_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_logged_with_oauth',
            field=models.BooleanField(default=False),
        ),
    ]
