# Generated by Django 4.2.16 on 2024-11-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0017_user_is_logged_with_oauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
