# Generated by Django 4.2.16 on 2024-11-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_remove_user_is_active_user_status'),
        ('UserManagement', '0018_alter_user_display_name'),
    ]

    operations = [
    ]
